[[websites.hoyoyo.searches]]
# 搜索关键字或者链接
# 必填项，str
keyword = "家庭教師ヒットマンREBORN"

# 通知方式
# from * to *
# 必填项
# 第一项 @Samiya310Bot（1），@Lihahadear_bot（2），企业微信Samiya（3）
# 第二项 根据notify中填的ids定
notify = [1,1]

delay = 1
user_max_pages = 20