# Suruga-Ya（骏河屋）配置
# 官网: https://www.suruga-ya.jp/

# Suruga-ya 网站的搜索设置
[[websites.suruga.searches]]
# 搜索关键字或者链接，必填项
keyword = "https://www.suruga-ya.jp/search?category=10&search_word=%E5%AE%B6%E5%BA%AD%E6%95%99%E5%B8%AB%E3%83%92%E3%83%83%E3%83%88%E3%83%9E%E3%83%B3REBORN+-%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88+-%E7%94%9F%E5%86%99%E7%9C%9F&adult_s=1&ck=true&hendou=%E6%96%B0%E5%85%A5%E8%8D%B7&inStock=On&is_marketplace=0&rankBy=modificationTime%3Adescending"

# 通知方式
# 必填项
# @Samiya310Bot（1），@Lihahadear_bot（2），企业微信Samiya（3）
notify = [1,1]

delay = 180
push_price_changes = false
user_max_pages = 20

[websites.suruga.searches.filter]