version: '3.8'
services:
  VintageVigil:
    image: samiya777/vintagevigil:alpine
    container_name: vintagevigil-364471371
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    volumes:
      - /root/VintageUser/.env:/root/VintageVigil/.env
      - ./notify.toml:/root/VintageVigil/user/364471371/notify.toml
      - ./logs:/root/VintageVigil/user/364471371/logs